### PR TITLE
Add patch for or-tools

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
I tentatively created this patch based on https://github.com/conda-forge/staged-recipes/pull/16147#issuecomment-920336371 but I'm not sure if this is the only thing required...

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
Should the previous uploads be marked as broken or what's the correct approach here?

**Comment by BastianZim** [comment]
Thanks, that was easier than I though. 😄

**Comment by wolfv** [comment]
You could try rebuilding or-tools in 1 hour or so. If it works, great! If not, we might have to fix other coin-or packages

**Comment by BastianZim** [comment]
Ok seems like that didn't fix everything yet. At least two more tools need fixing and there is a _libopenblas_ error where I'm not even sure where that's coming from. 😄

Happy to create the PRs for these errors but someone would have to tell me what to patch and where as I don't know C at all.

**Pull request merged**
