### PR TITLE
Update to 2.11.11 and add windows build

### PR DESCRIPTION
**Pull request by jpfeuffer**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Closes #16, closes #15, closes #3, closes #1

### CODE REVIEW

**Comment by tkralphs** [comment]
I guess I wasn't recommending to remove BLAS on Linux and MacOS. This would indeed be a regression and since everything is and has been working fine with BLAS there, I don't see a reason to change it. It is only the linking to BLAS on Windows that is a separate issue, not the linking to BLAS on all platforms. We could consider linking to `libcblas` on non-windows, though, which would hopefully mean we don't need Fortran at all on any platform. So maybe add back in `libcblas` and see if it gets picked up on non-Windows. It doesn't hurt to have it available on all platforms, it just won't be picked up on Windows.

**Comment by jpfeuffer** [comment]
Works now. Including cblas on Win and all other Fortran stuff on unix.

**Comment by tkralphs** [comment]
Great! I couldn't see what you did to get `cblas.lib` and `lapack.lib` to be installed on Windows. When I installed the `cblas` conda package locally, I didn't get the static libraries, as far as I could see. Anyway, great that it's all working now, but LAPACK was not being linked on Windows. I know you had asked about it yesterday. Yes, it is also good to link LAPACK. I committed a change to add that for Windows as well.

**Comment by tkralphs** [comment]
Hmm, I don't know why the CI jobs on Azure are not being launched.

**Comment by jpfeuffer** [comment]
Will lapack require a fortran compiler?

**Comment by jpfeuffer** [comment]
Apparently not.

**Review by tkralphs — APPROVED** [review]

**Comment by tkralphs** [comment]
Everything looks great now, finally!

**Comment by jpfeuffer** [comment]
@wolfv @h-vetinari Any comments? This should be much faster to review than the previous PR on which you both had a look already.

**Comment by tkralphs** [comment]
@jpfeuffer Should we just merge? I'm still working on releases for the rest of the stack, but [Osi](https://github.com/conda-forge/coin-or-osi-feedstock) is done and I will push on the rest if we can get this done.

**Comment by jpfeuffer** [comment]
On the one hand, I am pretty confident that I addressed the comments from last time. With the new PR also the commit history looks much better.
On the other hand, they might not have been fully done with their reviews.

But I think there is nothing that could not be fixed with a smaller follow-up PR.

**Comment by h-vetinari** [comment]
Sorry, haven't had time for this recently. From a quick look this looks good to me, so feel free to go ahead!

**Comment by jpfeuffer** [comment]
Yay! Yes, I will give it a try!

**Pull request merged**
