### PR TITLE
Try win

### PR DESCRIPTION
**Pull request by wolfv**
@tkralphs this is a try to see if we can get a build on win working. 

The win build executes the `bld.bat` file, but that one uses the `m2-bash` package to run bash, and execute the `build.sh` file (same one that we use for the OS X and Linux builds.

Locally I get the following output:

```
bash.exe: warning: could not find /tmp, please create!
bash.exe: warning: could not find /tmp, please create!
bash.exe: warning: could not find /tmp, please create!
bash.exe: warning: could not find /tmp, please create!
mkdir: cannot create directory '/tmp/cg14648-31583': No such file or directory
mkdir: cannot create directory '/tmp/cg-14648': No such file or directory
config.guess: cannot create a temporary directory in /tmp
configure: error: cannot guess build type; you must specify one
```

### CODE REVIEW

**Comment by wolfv** [comment]
@conda-forge-admin rerender

**Comment by tkralphs** [comment]
I'm still trying to see how all this hangs together, but you might need the `--enable-msvc` argument to configure. This doesn't do much except for making the `cl` compiler preferred over `gcc`. I think if the variables `CC` and `CXX` are set somewhere to `cl`, than it may not matter. I'm not sure exactly what to with the lack of `/tmp`, but there must be a way of using the autotools within the MSys2 setup provided and using `/tmp` would be a standard thing. Can you remind me how to run the build locally?

**Comment by wolfv** [comment]
Hi @tkralphs to build locally you can either run the build-locally.py script in this repo, or you can run `conda build`:

First you should add conda-forge as channel: 

```
conda config --add channels conda-forge
```

Update conda (I use the base environment for conda-build): `conda update --all`
Then just install conda build with `conda install conda-build`
And run:

```
cd coin-or-utils-feedstock
conda build recipe/
```

**Comment by wolfv** [comment]
Hi @tkralphs the error looks "better" now: 

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=214696&view=logs&jobId=a70f640f-cc53-5cd3-6cdc-236a1aa90802&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f

Apparently the uname is MSYS_NT-10.0... and not picked up by config.guess? I am not an expert with autotools, maybe you have an idea?

**Comment by tkralphs** [comment]
Oops, yes, this error is a known issue with the old version of the autotools we are using in 2.10.5 (this is fixed in master), which I forgot about. Adding `--host=i686-w64-mingw32` to configure should address it.

**Comment by tkralphs** [comment]
Sorry, I meant `--build=x86_64-w64-mingw32`!

**Comment by tkralphs** [comment]
Progress! Not sure exactly what's happening now.  It seems to be trying to link to Blas, although configure seems to say that it was not found.  I'll dig into that a bit. `configure` says 
```
checking whether source of project Blas is available and should be compiled... no, --with-blas-lib has been specified
```
but it's still trying to link. There are Blas and Lapack libraries available on MSys2. Can we install them or does it not make sense? I usually install these libraries for builds on Msys2.
```
mingw-w64-x86_64-lapack mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-readline mingw-w64-x86_64-suitesparse mingw-w64-x86_64-metis
```

**Comment by tkralphs** [comment]
Hmm, OK, upon digging a little more, I was mis-reading the output. I forgot that we are running the top-level configure first, which recursively runs `CoinUtils/configure`. As I mentioned before (I think), in the master versions of these projects, there is no top-level configure, which simplifies things. Anyway, the message I quoted above was from the top-level configure, just saying that the COIN-OR ThirdParty wrapper project for CoinUtils is not available, which is correct. Once `CoinUtils/configure` itself is called, it is reporting 
```
checking for COIN-OR package Blas... yes
```
But it's apparently still not able to link in the end. I'm still trying to trace what could have happened, as this should not be able to occur, but haven't quite pinned it down. I'll try building locally later.

**Comment by tkralphs** [comment]
Hmm, there seems to be a bug in the use of `--with-blas-lib` that I'm still working out, but it looks like you can just use `--with-blas="${WITH_BLAS_LIB}" instead and that should work. It appears that the flags aren't correct, so by "work", I mean the configure script will properly report that the flags don't work and then we can try to figure out what they should be in the Windows case.

**Comment by wolfv** [comment]
sorry, maybe that was my fault! There is a "weird" convention on window to use a Library folder that contains the unix style prefix on windows.... so instead of $PREFIX it needs to be $LIBRARY_PREFIX.

**Comment by tkralphs** [comment]
OK, as long as the flags are correct, it should be fine, but what I just found out is that the link check isn't actually done when you specify the link flags with `--with-blas-lib`, but it is done when you specify the link flags with `--with-blas`. So it is still safer to use `--with-blas` (and `--with-lapack`) for now. We should fix that bug in a future release (although it is a bug in our old build system, which won't be used in newer versions).

By the way, I couldn't get the local build to work, but didn't have time to dig into it yet.  I just got the not-so-helpful message
```
Skipped: coin-or-utils from C:\Users\tkral\Documents\Projects\conda\coin-or-utils-feedstock\recipe defines
build/skip for this configuration ({'c_compiler': 'vs2015', 'cxx_compiler': 'vs2015', 'fortran_compiler': 'gfortran'}).
```
with no indication why it was skipped. I guess something it's looking for is not there, but it doesn't say what it is.

**Comment by tkralphs** [comment]
Still failing, maybe try with `--with-blas` instead? But that will probably only confirm that the flags are still wrong for some reason.

**Comment by tkralphs** [comment]
@wolfv Hope you don't mind, I just pushed a commit to your branch myself to see if I could figure anything out.

**Comment by tkralphs** [comment]
Sill fails, as expected, but now we get a real error:
```
configure: error: user supplied BLAS library "-LD:\bld\coin-or-utils_1601607263531\_h_env\Library/lib -lblas" does not work
```
The problem may be that "/" in the path should be "\".

**Comment by tkralphs** [comment]
No dice... will need to do some more digging.

**Comment by wolfv** [comment]
that's great! yeah I also tried a little bit more a couple days ago but couldn't get it to work ... thanks for looking into this!

We could also try another BLAS library (e.g. MKL?) but I am not sure if that's the issue. 
regarding back- vs forward slashes I had the feeling that Windows would handle that OK these days...

**Comment by wolfv** [comment]
I tested some more locally, and this is the output from the inner config.log:

configure:30150: checking whether user supplied BLASLIB="C:/Users/wolfv/Miniconda3/conda-bld/coin-or-utils_1603092343187/_h_env/Library/lib/blas.lib" works with C linkage
configure:30158: checking for daxpy
configure:30223: cl.exe -o conftest.exe -MT -O2 -nologo -wd4996 -D_CRT_SECURE_NO_DEPRECATE -DNDEBUG    -DCOINUTILS_BUILD   conftest.c C:/Users/wolfv/Miniconda3/conda-bld/coin-or-utils_1603092343187/_h_env/Library/lib/blas.lib  >&5
conftest.c
conftest.obj : error LNK2001: unresolved external symbol daxpy
conftest.exe : fatal error LNK1120: 1 unresolved externals
cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
configure:30229: $? = 2
configure: failed program was:
| /* confdefs.h.  */
| 
| #define PACKAGE_NAME "CoinUtils"
| #define PACKAGE_TARNAME "coinutils"
| #define PACKAGE_VERSION "2.11.4"
| #define PACKAGE_STRING "CoinUtils 2.11.4"
| #define PACKAGE_BUGREPORT "http://projects.coin-or.org/CoinUtils"
| #define COINUTILS_VERSION "2.11.4"
| #define COINUTILS_VERSION_MAJOR 2
| #define COINUTILS_VERSION_MINOR 11
| #define COINUTILS_VERSION_RELEASE 4
| #define COIN_COINUTILS_VERBOSITY 0
| #define COIN_COINUTILS_CHECKLEVEL 0
| #ifdef __cplusplus
| 
| #endif
| #define PACKAGE "coinutils"
| #define VERSION "2.11.4"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_CMATH 1
| #define HAVE_CFLOAT 1
| #define COIN_C_FINITE _finite
| #define HAVE_CMATH 1
| #define HAVE_CFLOAT 1
| #define COIN_C_ISNAN std::isnan
| #define COINUTILS_MEMPOOL_MAXPOOLED -1
| #define HAVE_CINTTYPES 1
| #define HAVE_CSTDINT 1
| #define COIN_INT64_T int64_t
| #define COIN_UINT64_T int64_t
| #define COIN_INTPTR_T intptr_t
| #define COINUTILS_HAS_CSTDINT 1
| #define HAVE_WINDOWS_H 1
| /* end confdefs.h.  */
| /* Define daxpy to an innocuous variant, in case <limits.h> declares daxpy.
|    For example, HP-UX 11i <limits.h> declares gettimeofday.  */
| #define daxpy innocuous_daxpy
| 
| /* System header to define __stub macros and hopefully few prototypes,
|     which can conflict with char daxpy (); below.
|     Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
|     <limits.h> exists even on freestanding compilers.  */
| 
| #ifdef __STDC__
| # include <limits.h>
| #else
| # include <assert.h>
| #endif
| 
| #undef daxpy
| 
| /* Override any gcc2 internal prototype to avoid an error.  */
| #ifdef __cplusplus
| extern "C"
| {
| #endif
| /* We use char because int might match the return type of a gcc2
|    builtin and then its argument prototype would still apply.  */
| char daxpy ();
| /* The GNU C library defines this for functions which it implements
|     to always fail with ENOSYS.  Some functions are actually named
|     something starting with __ and the normal name is an alias.  */
| #if defined (__stub_daxpy) || defined (__stub___daxpy)
| choke me
| #else
| char (*f) () = daxpy;
| #endif
| #ifdef __cplusplus
| }
| #endif
| 
| #ifdef F77_DUMMY_MAIN
| 
| #  ifdef __cplusplus
|      extern "C"
| #  endif
|    int F77_DUMMY_MAIN() { return 1; }
| 
| #endif
| int
| main ()
| {
| return f != daxpy;
|   ;
|   return 0;
| }
configure:30254: result: no
configure:30259: error: user supplied BLAS library "C:/Users/wolfv/Miniconda3/conda-bld/coin-or-utils_1603092343187/_h_env/Library/lib/blas.lib" does not work


I checked blas.lib with `dumpbin /exports blas.lib` and it prints:

Dump of file blas.lib                                                                                                                                                                                                                                     File Type: LIBRARY                                                                                                                                                                                                                                             Exports                                                                                                                                                                                                                                                     ordinal    name                                                                                                                                                                                                                                                      caxpy_                                                                                                                       ccopy_                                                                                                                       cdotc_                                                                                                                       cdotu_                                                                                                                       cgbmv_                                                                                                                       cgemm_                                                                                                                       cgemv_                                                                                                                       cgerc_                                                                                                                       cgeru_                                                                                                                       chbmv_                                                                                                                       chemm_                                                                                                                       chemv_                                                                                                                       cher2_                                                                                                                       cher2k_                                                                                                                      cher_                                                                                                                        cherk_                                                                                                                       chpmv_                                                                                                                       chpr2_                                                                                                                       chpr_                                                                                                                        crotg_                                                                                                                       cscal_                                                                                                                       csrot_                                                                                                                       csscal_                                                                                                                      cswap_                                                                                                                       csymm_                                                                                                                       csyr2k_                                                                                                                      csyrk_                                                                                                     
```


so it looks like daxpy would be there, but with an underscore at the end?!

I also checked out `cblas.lib` and it exports the symbols with `cblas_daxpy` etc.

Any ideas @tkralphs ?

**Comment by wolfv** [comment]
In the above test code, when I change `daxpy` to `daxpy_` and link to `blas.lib` it works fine. I am going to ask on the chat: https://gitter.im/conda-forge/conda-forge.github.io

**Comment by wolfv** [comment]
maybe it has something to do with no F77 compiler being found? and therefore the name mangling isn't correctly adding an underscore?

**Comment by tkralphs** [comment]
Yes, you are probably right. There is some logic for name mangling, but it does seem to only get invoked when a Fortran compiler is present. But I'm not sure why we don't have this issue in general. I believe I am able to build and link to Blas and Lapack with `cl` and with no Fortran compiler in a standard MSy2 build. Or perhaps we do have `gfortran` present, although we do not use it and this fixes things. 

This is one of the many things that are fixed up in the new version of the `BuildTools`, which is used in `CoinUtils` master. All the name mangling stuff is done differently and not only when there is a Fortran compiler present. I'm working on getting master out into release for the whole Cbc stack and once this happens, we may not care so much about the 2.10 stack. This may be something we just set aside for now. But I guess it's worth poking at it a little. Maybe just install `gfortran`?

**Pull request closed without merging**
